---
title: "BIOL4315_Lab4_Assembly_Annotation"
author: "OceanneYW"
date: "2025-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download ***Arabidopsis thaliana ref genome***
```{bash conda, eval=FALSE}
wget -nc https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz

```

## Packages installation
```{r, eval=FALSE, echo=FALSE}
#BiocManager::install("clusterProfiler")
#BiocManager::install("EnhancedVolcano")

#Note, if biomaRt isn't installed on your machine for some reason, you should install it as well. 

lapply(c(
  "docopt", "DT", "pheatmap","GenomicFeatures", "DESeq2",
  "edgeR", "systemPipeR", "systemPipeRdata", "BiocStyle", "GO.db", "dplyr",
  "tidyr", "stringr", "Rqc", "QuasR", "DT", "ape", "clusterProfiler","biomaRt","EnhancedVolcano"
), require, character.only = TRUE)

#hisat2 checked
```

## 4.1 Accessing the RNAseq data and sample data
```{r sample data loading, echo=FALSE, eval=TRUE}
#e.g.1 get the path 
fq_path <- systemPipeRdata::pathList()$fastqdir

#e.g.2 list the files 

fq_files <- list.files(fq_path)

print(fq_files)

```
```{r Read meta data, echo=TRUE, eval=FALSE}
meta_data <- read.table('/Users/owang/Library/R/arm64/4.4/library/systemPipeRdata/extdata/param/targetsPE.txt', header = TRUE)
head(meta_data)
```

### 4.1.1 Question1
```{r replace pathways, eval=TRUE, echo=TRUE}
library(stringr)
library(data.table)

setDT(meta_data)[,"FileName1" := str_replace(meta_data$FileName1, "./data/", fq_path)]
setDT(meta_data)[,"FileName2" := str_replace(meta_data$FileName2, "./data/", fq_path)]
head(meta_data)
```

### 4.2 Read Processing
```{r, eval=TRUE}
library(Rqc)

fileList <- list.files(path = fq_path, pattern = ".fastq.gz", full.names = TRUE)
pair_vector <- rep(1:3, each=2)
fqFiles <- lapply(1:4, function(x) {rqc(path = ".", pattern = ".fastq.gz", pair=c(1,1), openBrowser = FALSE)})
#qualityBoxPlot <- rqcCycleQualityBoxPlot(rqc(path = fq_path, pattern = ".fastq.gz", openBrowser = FALSE))

qualityBoxPlot
```

### 4.2.2 
```{r, eval=TRUE}
#BiocManager::install("QuasR")

library(QuasR)
library(ShortRead)


```